version: 2

jobs:
  quality:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./mvnw clean test -Dspring.profiles.active=test
      - run:
          name: Upload coverage report
          command: bash <(curl -s https://codecov.io/bash)